### ISSUE TITLE
Empty panels on homepage when viewing on Firefox on Android

### ISSUE THREAD

**Issue by stevejalim** [mozilla/stateof#10]
Hi there - thanks for making the site work on FF Mobile!

I just checked it out and noticed a chunk of dead space on the homepage when I scroll down far - you can see it at the start of this video. Hopefully it's not a pain to fix.

https://github.com/mozilla/stateof/assets/101457/e2e53282-c01a-4354-9208-246dc2e08afe

Also, when side-swiping between pages/modals on mobile, is it possible to scroll to the top so that it's easier to see what the next text is about, please?

**Comment by wuebkers** [comment]
@stevejalim are you able to provide what browser version and device you are on? I am unable to reproduce the issue on a Google Pixel 7, nor a Galaxy S23.

https://github.com/mozilla/stateof/assets/9771335/cc2bef68-d6d7-4ddc-afc3-2f96105b0592

**Comment by stevejalim** [comment]
Hi @wuebkers it's Firefox Android 120.1.0 on a Pixel 7a

**Comment by stevejalim** [comment]
I just tried using remote debugging to see if devtools had any insight. 

There wasn't really anything obvious in the console:

<img width="1907" alt="Screenshot 2023-12-07 at 13 49 20" src="https://github.com/mozilla/stateof/assets/101457/178be763-cf06-493d-a697-e037cf208744">

However, when I viewed source via Inspector, I could see that all of the missing elements still had a `hidden` attr on their root node. Removing it then displayed a black-framed box, but no actual content. I wonder if that means there's a branch of elements that are stuck on `hidden` somehow? Apols but no screenshot available right now

Hope that helps a bit. Happy to do some proper remote debugging if there's something specific I can seek for you

**Comment by stevejalim** [comment]
Ah ha - I was bouncing this around with @alexgibson and we (really: he) hit upon a simple way to replicate:

> the bug happens in any browser (Chrome, too) if you set the window less than 350px wode

(The CSS pixel width of my Pixel 7a is 324px)

Hopefully this'll help a lot in getting it sorted @wuebkers. Cheers!

**Comment by wuebkers** [comment]
@stevejalim can you look at this preview and confirm with me this is fixed on your end? Once confirmed, I'll get this merged in and up on live:
https://deploy-preview-11--stateof-mozilla.netlify.app/

**Comment by stevejalim** [comment]
@wuebkers Yep, that works for me both on my physical phone and in FF devtools. Thanks for the fixup.

Playing in devtools and reloading after every width adjustment, it does look like the issue still occurs with a viewport _below_ 320px, but it certainly works now on devices wider than that. (I don't think there'll be much around that has a screen smaller than 320px)

**Comment by stevejalim** [comment]
Thanks for the fix!
